### ISSUE TITLE
Duplicate Availability Times: Voting Page

### ISSUE THREAD

**Issue by capple2016** [jakesboy2/MeetingScheduler#41]
When adding availability times to a user on the voting page, the times start to duplicate.
 
![Duplicates are automatically generated](https://user-images.githubusercontent.com/35755160/76676424-5fcaa200-6591-11ea-8520-414aa82bcd79.PNG)

**Comment by capple2016** [comment]
Maybe related but the names of the users (A, B, C) are also duplicated in the results.
![Duplicate results](https://user-images.githubusercontent.com/35755160/76676510-2cd4de00-6592-11ea-9d73-5bdd919d4938.PNG)

**Comment by ghost** [comment]
I fixed the bug. but the generate meeting time just show results of all the comparisons so it still duplicates some.
