### ISSUE TITLE
Invitee name does not show up: Projects Page

### ISSUE THREAD

**Issue by capple2016** [jakesboy2/MeetingScheduler#42]
I'm not sure if this is supposed to be a feature or not but the name of the invited does not show up as it does for the owner and active users.
![Name of Invited](https://user-images.githubusercontent.com/35755160/76676763-92c26500-6594-11ea-8ecc-dbc3797f009f.PNG)

**Comment by calebpower** [comment]
The display name of that user doesn't exist. It's probably the "admin" user, that doesn't have a display name set by default. You can set one in the admin panel.

**Comment by calebpower** [comment]
Assigned @jakesboy2 because user creation is his domain.

**Comment by capple2016** [comment]
Ahh, you're right. It was the admin. Works fine with a regular username. Honestly, admin probably shouldn't be considered an actual user.
