### ISSUE TITLE
Outdated libraries in "availability" pages break cross-site functionality.

### ISSUE THREAD

**Issue by calebpower** [jakesboy2/MeetingScheduler#43]
The outdated jQuery and Bootstrap libraries in `/meeting/templates/availability/js.html` are breaking the navbar, notifications, and other cross-site functionality.

**Comment by jhampton6** [comment]
Is this still a problem after I refactored so the old libraries are only loaded on the Availability page?

**Comment by calebpower** [comment]
Yeah, because anything that's cross-site will be broken on that page. I.e. when people are on the Availability page, they won't get notifications.

**Comment by jhampton6** [comment]
Oh, I see. Alright, I'll move to that other datetime picker and get rid of the old library dependency next sprint.
