### ISSUE TITLE
Github Cleanup

### ISSUE THREAD

**Issue by calebpower** [jakesboy2/MeetingScheduler#75]
Hi all, long time no see.

I'm planning on moving this repo to my account so I can clean up my GitHub space-- I've got too many wayward groups hanging out. Y'all should be able to fork this repo if you want it in your portfolios-- I'll probably end up moving it in a couple of days. (I'm not sure where everyone's email is, so I figured that this is as good of a place as any to put this.) Please let me know if there are any objections! Also, if anyone is interested in continuing this project at all, please don't hesitate to reach out. It might be a good opportunity to turn this into an open-source SaaS project after some cleanup.

Thank you!

**Comment by capple2016** [comment]
No objections from me!
